services:
  mysql:
    image: mysql:latest
    restart: unless-stopped
    ports:
      - "${DB_PORT:-3306}:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
      MYSQL_DATABASE: "${DB_DATABASE}"
      MYSQL_USER: "${DB_USERNAME}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    volumes:
      - "./mysql/db:/var/lib/mysql"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping"]
    networks:
      - shockbot

networks:
  shockbot:
    driver: bridge